version: "3"
networks:
  frontend:
  backend:
volumes:
  pgdata:
  appdata:
services:
  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_DB: app
    networks:
      backend: {}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:4
    networks:
      backend: {}

  web:
    build: .
    command: "./docker/web"
    depends_on:
      - postgres
      - redis
      - worker
    volumes:
      - appdata:/app/files
    restart: unless-stopped
    networks:
      frontend:
      backend:

  worker:
    build: .
    command: "./docker/worker"
    depends_on:
      - postgres
      - redis
    volumes:
      - appdata:/app/files
    networks:
      backend:
    restart: unless-stopped
