version: "3"
services:
  web:
    env_file:
      - .env.staging
  worker:
    env_file:
      - .env.staging
  proxy:
    image: caddy:2-alpine
    environment:
      - SITE_FQDN=${PULLPREVIEW_PUBLIC_DNS}
      - SITE_PASSWORD
    command: "/docker/caddy/run"
    restart: unless-stopped
    volumes:
      - "./docker/caddy:/docker/caddy"
    depends_on:
      - web
    networks:
      - frontend
    ports:
      - "443:443"
      - "80:80"
